### ISSUE TITLE
Issue with deploying Drone Runner on GKE Autopilot - Connection and Permission Errors

### ISSUE THREAD

**Issue by syhlion** [drone/charts#115]
Description:
I deployed Drone Runner on GKE Autopilot following the official documentation, and my parameter settings are as follows:

```
env:
  DRONE_RPC_SECRET: test
  DRONE_SECRET_PLUGIN_ENDPOINT: http://drone-kubernetes-secrets:3000
  DRONE_SECRET_PLUGIN_TOKEN: test
  DRONE_RUNNER_NETWORK_OPTS: "com.docker.network.driver.mtu:12345"
dind: 
  commandArgs:
    - "--host"
    - "tcp://localhost:2375"
    - "--mtu=12345"
  securityContext:
    privileged: false

podSecurityContext:
  fsGroup: 2000
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
```
However, when I check the logs of the Runner pod, I encountered the following errors:

```
grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///var/run/docker/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.9 (legacy): can't initialize iptables table `nat': Permission denied (you must be root)
```

I'm seeking assistance on how to resolve and adjust the configuration for the mentioned issues.

Thank you.
