### ISSUE TITLE
I use the charts to make up a drone server, but the trigger doesn't work 

### ISSUE THREAD

**Issue by golanggc** [drone/charts#25]

**Comment by golanggc** [comment]
# my pipeline is here
kind: pipeline
type: kubernetes
name: default
dns_config:
  nameservers:
    - 192.168.0.63
    - 172.21.0.10
steps:
- name: greeting
  image: alpine
  commands:
  - echo world
trigger:
  event:
  - push

**Comment by golanggc** [comment]
# my pipeline
```
kind: pipeline
type: kubernetes
name: default
dns_config:
  nameservers:
    - 192.168.0.63
    - 172.21.0.10
steps:
- name: greeting
  image: alpine
  commands:
  - echo world
trigger:
  event:
  - push
```
