### ISSUE TITLE
stuck in state `default: Pending` on gcloud k8s cluster

### ISSUE THREAD

**Issue by kushwahashiv** [drone/charts#28]
I tried to follow the steps mentioned here https://github.com/drone/charts.

I created a k8s cluster on gcloud and performed in sequence below steps:

1. k8s in google cloud I can access from my machine.

2. I added chart in helm
```cmd
helm repo add drone https://charts.drone.io
helm repo update
```
3. I created `drone-values.yaml`
```yaml
service:
  type: LoadBalancer
env:
  DRONE_SERVER_HOST: drone.example.com
  DRONE_SERVER_PROTO: http
  DRONE_RPC_SECRET: secret
  DRONE_GITHUB_CLIENT_ID: xxxxxxxxxxxxxxxxxxxxxxx
  DRONE_GITHUB_CLIENT_SECRET: yyyyyyyyyyyyyyyyyyyyy
  DRONE_USER_CREATE: username:kushwahashiv,admin:true
```
4. installed drone 
```cmd
kubectl create ns drone
helm install --namespace drone drone drone/drone -f drone-values.yaml
```
All the pods were created and running 

5. I created a file `rone-runner-kube-values.yaml` with below content

```yaml
rbac:
  buildNamespaces:
    - drone

env:
  DRONE_RPC_SECRET: secret
  DRONE_NAMESPACE_DEFAULT: drone

```
6. Installed runner
```cmd
helm install --namespace drone drone-runner-kube drone/drone-runner-kube -f drone-runner-kube-values.yaml
```

All the pods running successfully.

7. When I sync repos and try to change the repo it triggers a build 

![image](https://user-images.githubusercontent.com/4386810/103030436-a7169380-4510-11eb-9e47-68db86da6680.png)

Above build is now stuck for forever in a `default: Pending` state

I'm not sure which step I'm missing to setup the drone on google cloud.
