### ISSUE TITLE
Helm charts requires DRONE_RPC_SECRET when it may already be provided by extraSecretNamesForEnvFrom secret

### ISSUE THREAD

**Issue by danieldsj** [drone/charts#5]
PROBLEM
When providing secrets using the extraSecretNamesForEnvFrom method, helm3 still raises an error that the DRONE_RPC_SECRET environment variable is missing.

STEPS
1. Create a Kubernetes environment, setup Helm 3, add the drone repo, and update. (I used microk8s for this)
2. Create a `drone` namespace.
3. Create a `drone-secret` Kubernetes secret in the `drone` namespace similar to the following...
```
apiVersion: v1
kind: Secret
metadata:
  name: drone-secret
  namespace: drone
data:
  DRONE_RPC_SECRET: ***
  DRONE_GITHUB_CLIENT_ID: ***
  DRONE_GITHUB_CLIENT_SECRET: ***
```
4. Create a values file that makes reference to the secret that looks similar to the following...
```
service:
  type: LoadBalancer
 
extraSecretNamesForEnvFrom:
  - drone-secret

env:
  DRONE_SERVER_HOST: drone.domain.local
  DRONE_SERVER_PROTO: https
```
5. Attempt to install drone using the helm chart using a command similar to the following:
6. Observe.

OBSERVED
The command returns the following error:
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
drone:
- env: DRONE_RPC_SECRET is required
```

EXPECTED
The `DRONE_RPC_SECRET` would be pulled from the Kubernetes Secret, so it should not be prompting the user as if it was not already provided.

WORKAROUND
Add a bogus value for the DRONE_RPC_SECRET environment variable in the values.yaml file.

SOLUTION
Remove references to DRONE_RPC_SECRET from the required properties in the `values.schema.json` file.
This can be done in the following places:
https://github.com/drone/charts/blob/dd2668e7f41f508b72274daeaf97caf840d26f1e/charts/drone/values.schema.json#L153
https://github.com/drone/charts/blob/dd2668e7f41f508b72274daeaf97caf840d26f1e/charts/drone-runner-kube/values.schema.json#L168
