### ISSUE TITLE
dron runner SA lacks required credentials

### ISSUE THREAD

**Issue by kamilgregorczyk** [drone/charts#60]
after installing 
```
helm upgrade drone-runner drone/drone-runner-kube --install --create-namespace --namespace drone --values runner.yaml
```

with values:

```
replicaCount: 2
env:
  DRONE_RPC_SECRET: aaaa
  DRONE_NAMESPACE_DEFAULT: drone
```

I'm getting 
```
default: secrets is forbidden: User "system:serviceaccount:drone:drone-runner-drone-runner-kube" cannot create resource "secrets" in API group "" in the namespace "drone"
``` when running a pipeline
