### ISSUE TITLE
Unable to start a new build: json: cannot unmarshal number into Go value of type gogs.commitDetail

### ISSUE THREAD

**Issue by kaybinwong** [drone/charts#71]
error happens where new build after install by charts.
![image](https://user-images.githubusercontent.com/5570216/170684574-421df03d-a4bb-4627-ab81-1237c2632361.png)

Unable to start a new build: json: cannot unmarshal number into Go value of type gogs.commitDetail

![image](https://user-images.githubusercontent.com/5570216/170685013-45644928-96b4-411e-8927-4792fd390533.png)

here is the .drone.yml file
```
---
kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo world
trigger:
  event:
  - push
```
